import "pnpm/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between bg-white p-4 text-xl font-semibold mr-1 border-b p-4">
      <div>
         
          Gallary
        
      </div>
      <div>
       
          Sign In
        
      </div>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`font-sans $schema="{inter.variable} flex flex-col gap-4`}><TopNav />
      {children}

      </body>
    </html>
  );
}
