import "@uploadthing/react/styles.css";

import "pnpm/styles/globals.css";
 
import { ClerkProvider } from "@clerk/nextjs";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import TopNav from "./_component/topnav";

export const metadata: Metadata = {
  title: "T3 Gallary",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`font-sans $schema="{inter.variable} flex flex-col gap-4`}><TopNav />
      {children}

      </body>
    </html>
    </ClerkProvider>
  );
}
